### PR TITLE
Remove django-allauth-2fa, dj-rest-auth and django-user-sessions    

### LINKED ISSUE #6281: Remove django-allauth-2fa
We are currently using the awesome django-allauth-2fa. The upstream project django-allauth has added mfa recently and seems to support pretty much everything django-allauth does so IMO it is time to reduce the depency tree and remove django-allauth-2fa.

There are actually docs for this: https://docs.allauth.org/en/latest/mfa/django-allauth-2fa.html.
Although it should not really be breaking, I would still consider it as such as this is probably a one-way street.

### LINKED ISSUE #8708: [UI] Multifactor token configuration
Multifactor authentication setup is missing in the new admin center:

Image

### LINKED ISSUE #8949: New Interface - Unable to Login with Google SSO
### Please verify that this bug has NOT been raised before.

- [x] I checked and didn't find a similar issue

### Describe the bug*

'GenericOAuth2ApiLoginView' object has no attribute 'login'

Traceback (most recent call last):

File "/root/.local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/root/.local/lib/python3.11/site-packages/allauth/socialaccount/providers/oauth2/views.py", line 105, in view
return self.dispatch(request, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/home/inventree/src/backend/InvenTree/InvenTree/social_auth_urls.py", line 33, in dispatch
return self.login(request, *args, **kwargs)
^^^^^^^^^^

AttributeError: 'GenericOAuth2ApiLoginView' object has no attribute 'login'

### Steps to Reproduce

1. Open a new (incognito) screen
2. Open the login page
3. Login with SSO
4. Confirm the SSO redirect

Internal Server Error
The server raised an internal error
Refer to the error log in the admin interface for further details

### Expected behaviour

Expected to be redirected to Google for a login.

The login process works properly in the previous (original?) UI. That is I am redirected to Google to enter my credentials. 

### Deployment Method

- [x] Docker
- [ ] Package
- [ ] Bare metal
- [ ] Other - added info in Steps to Reproduce

### Version Information

# Version Information:
InvenTree-Version: 0.17.2
Django Version: 4.2.17
Commit Hash: 4b56492
Commit Date: 2025-01-07

Database: postgresql
Debug-Mode: False
Deployed using Docker: True
Platform: Linux-6.11.0-13-generic-x86_64-with
Installer: DOC

Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.1.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}, {'name': 'InvenTreeCurrencyExchange', 'slug': 'inventreecurrencyexchange', 'version': '1.0.0'}, {'name': 'InvenTreeLabel', 'slug': 'inventreelabel', 'version': '1.1.0'}, {'name': 'InvenTreeLabelMachine', 'slug': 'inventreelabelmachine', 'version': '1.0.0'}, {'name': 'InvenTreeLabelSheet', 'slug': 'inventreelabelsheet', 'version': '1.0.0'}, {'name': 'DigiKeyPlugin', 'slug': 'digikeyplugin', 'version': '1.0.0'}, {'name': 'LCSCPlugin', 'slug': 'lcscplugin', 'version': '1.0.0'}, {'name': 'MouserPlugin', 'slug': 'mouserplugin', 'version': '1.0.0'}, {'name': 'TMEPlugin', 'slug': 'tmeplugin', 'version': '1.0.0'}]

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

### Relevant log output

```shell
The bug is not reproducible on the demo site because of the use of SSO.
```

### PR DESCRIPTION
**Pull request by matmair**
This PR remove django-allauth-2fa and replaces it with the inline functions of django-allauth. This reduces the dependency footprint and eliminates a bunch of custom creations.
It also adapts the schema generation process to include all allauth endpoints (they do not use DRF so normal generation is not working).

Update: Most of the planned things we would be interested in are now implemented and the scope shifted a bit - it makes sense to just ripp all auth extensions out and use only allauths built-in things. We have a lot of grown auth-adjacent code that can probably be removed/rewritten.

### Related Issues

- Closes #6281
- Closes #8708
- Closes #8949

### TODO 
- [x] refactor authentication forms && detection of enabled features (see 8912)
- [x] implement custom link target lookup for email from django-allauth
- [x] show user ID in MFA flow
- [x] implement email verification flow
- [x] re-implement registration flow
- [x] re-implement password reset flow
- [x] re-implement password change
- [x] keep auth context somewhere for the local session to refer back to
- [x] move now removed system status info into main status (registration, mfa, sso available)
- [x] switch back to browser flow for auth APIs
- [x] rename all new auth URLs to fix to the current schema
- [x] include schema for auth with central API
- [x] write changelog

[Coverage](https://app.codecov.io/gh/inventree/InvenTree/pull/6293?dropdown=coverage)

This relies on several upstream PRs:
- https://codeberg.org/allauth/django-allauth/pulls/4236 (custom frontend URLs)
- https://codeberg.org/allauth/django-allauth/pulls/4235 (allowing email registration even if MFA is enabled)

### CODE REVIEW

**Comment by matmair** [comment]
Upstream is not supporting enforced MFA right now - postboning to 0.16.0

**Comment by matmair** [comment]
OK MFA enforcing can be build by us and upstreamed but https://github.com/pennersr/django-allauth/issues/3830 is a new blocking

**Comment by matmair** [comment]
Site-Note: It seems I always end up ripping out/replacing the features I write

**Comment by matmair** [comment]
@sur5r this re-implements the MFA stack and now keeps the user completely in PUI. It is not fully done but I would appreciate if you could test this and report back. Please do this on a test-database, we are migrating the factors to a new DB schema so there could be issues.
Registering factors is not working currently but will be implemented before the merge.

**Comment by sur5r** [comment]
Will do, but might take some days before I get around to it.

@matmair could pass by at PoC desk if you have time?

**Comment by matmair** [comment]
@sur5r which PoC desk?

**Comment by sur5r** [comment]
At 38c3, first floor. https://38c3.c3nav.de/l/c:1:193.66:143.06/

**Comment by matmair** [comment]
I have removed #4002 for now as it is a good extra step and would a good first contribution for someone.

**Comment by matmair** [comment]
@SchrodingersGat @wolflu05 this is getting close; if you have time I would appreciate feedback on this already

**Comment by SchrodingersGat** [comment]
@matmair this looks like a fantastic improvement. I really appreciate that we can remove a lot of custom auth functionality here.

Have you performed any SSO testing as part of this? Is there any way that we can implement some automated CI testing of SSO auth somehow?

**Comment by matmair** [comment]
@SchrodingersGat I hope to get most if not all our custom things upstreamed - I am looking into contributing a few different things that we have built for ourselves up to django-allauth, send my first suggestion regarding this a few hours ago. This will help with better-separating concerns between different components.

I have tested SSO with GitHub and a few different OIDC providers extensively throught working on this. We are not modifing the logic  around this in any way so allauths tests should cover it. Adding CI testing would probably entail staging credentials for some provider into the CI - I am instinctly not a fan regarding this. I have not looked into that in more depth because we are just consuming the APIs.

**Comment by matmair** [comment]
All flows are now ported, now it is about cleanup and finishing a few smaller todos

**Comment by matmair** [comment]
This is done as far as possible right now; I am waiting on upstream to merge a few PRs so that this can get merged.
I would appreciate reviews, this should work in dev mode with the API being available on http://localhost:8000 (a PR to upstream needs to be merged to fix that limitation)

**Comment by matmair** [comment]
Upstream has merged what we need; this can be released after the 0.65.4 is released

**Comment by SchrodingersGat** [comment]
> Upstream has merged what we need; this can be released after 0.65.4 is released;

Do you mean upstream for [django-allauth](https://pypi.org/project/django-allauth/)?

**Comment by matmair** [comment]
@SchrodingersGat yes

**Comment by SchrodingersGat** [comment]
@matmair I indend to get to this soon to review and test

**Comment by matmair** [comment]
@SchrodingersGat @wolflu05 This is ready for review and merge.

There are many things I would like to improve in the future, but this PR would never ship if I made it feature complete to my liking. Here is a list of things that come to mind. I would wait for users to request and submit/fund these before doing them:
- Adding webauthn as a factor
- Dynamically showing and controlling if username or email is required
- Improving token issuance UX
- Adding sessions managment
- Moving all the Auth stuff into a separate Layout component
- e2e testing of SSO (that should be possible from a data flow view now)
- better management of email verifications
- adding better permission management into Admin Center
- adding better SSO provider setup into Admin Center
- adding a unified Authn/Authz setup and settings experience to Admin Center

File: src/frontend/src/pages/Index/Settings/AccountSettings/SecurityContent.tsx [hunk 1]
```diff
@@ -280,64 +260,401 @@ function SsoContent({ dataProvider }: Readonly<{ dataProvider: any }>) {
...
+      },
+      {
+        type: 'recovery_codes',
+        name: t`Recovery Codes`,
+        description: t`One-Time pre-generated recovery codes`,
+        function: registerRecoveryCodes,
+        used: usedFactors?.includes('recovery_codes')
+      }
+    ].filter((factor) => {
+      auth_config?.mfa.supported_types.includes(factor.type);
```
Comment (SchrodingersGat) [inline src/frontend/src/pages/Index/Settings/AccountSettings/SecurityContent.tsx:542]: Need to add a 'return' before this line, currently the possibleFactors method is returning an empty list

```javascript
return auth_config?.mfa.supported_types.includes(factor.type);
```

**Comment by SchrodingersGat** [comment]
Some notes:

### Login Conflict

If the user is already logged in, attempting a login causes a `409` error. This is throwing a `ConflictResponse` within allauth as the user is already authenticated. This can cause some very hard to debug behaviour (especially for the typical user) and we should consider how best to handle this.

Ref: https://github.com/pennersr/django-allauth/issues/4008

### Registering TOTP Code

When you register a new code (in my case, scan QR into google authenticator) but you enter the incorrect one-time code, there is no feedback / error information supplied. The screenshot below shows this - the API returns an error but there is no UI feedback

image

### Login via TOTP

If you put the wrong code into the login screen there is no error message

File: src/frontend/src/pages/Index/Settings/AccountSettings/SecurityContent.tsx (hunk 1 above)
Comment (SchrodingersGat) [reply src/frontend/src/pages/Index/Settings/AccountSettings/SecurityContent.tsx]: Note: I have pushed a fix for this one.

**Comment by SchrodingersGat** [comment]
### Basic Login

Basic login (username / password) continues to work as expected (aside from the `409` error as detailed above).

### TOTP Login

After making some small tweaks (see my commits above) I now have TOTP working - seems to function as expected.

- [x] Create new TOTP login
- [x] Test failure case during TOTP creation
- [x] Login via TOTP
- [x] Test failure case during TOTP login
- [x] Remove TOTP from user account
- [x] Normal login after TOTP removed

### SSO

...

**Comment by matmair** [comment]
The 409 error is only a problem if running the frontend separately from the backend (ie with the vite dev server). In the production setup, the logged-in check at the beginning of the flow will catch that.
I will add some error notification.

**Comment by matmair** [comment]
I think all the mentioned issues should be addressed now, let me know if there is anything else that needs fixing.

**Comment by wolflu05** [comment]
I'm really sorry, I won't have time currently for any review (that's why I answer so rarely). This is really a huge step for inventree to get rid of more old templating and a modernized login flow. Thank you really much for implementing this.

**Comment by SchrodingersGat** [comment]
@matmair thanks for adding that error message

I don't have a way of testing SSO for this currently - have you tested this? Against which providers?

**Comment by SchrodingersGat** [comment]
Regarding the playwright tests, looks like you are hitting some `500` errors:

image

image

**Comment by matmair** [comment]
@SchrodingersGat that is a database-locked error due to us running tests in parallel; this is normally fixed by just retrying a bit

**Comment by SchrodingersGat** [comment]
> @SchrodingersGat that is a database-locked error due to us running tests in parallel; this is normally fixed by just retrying a bit

Would it be worth (as a separate PR) moving to a postgres setup for the playwright testing in CI? We spend a significant amount of time retrying failed tests...

**Comment by matmair** [comment]
@SchrodingersGat any idea what this segmentation fault is? No idea how I introduced that

**Comment by matmair** [comment]
@SchrodingersGat this finally is all green!

**Comment by SchrodingersGat** [comment]
Great news! Some conflicts to fix now now though :)

Re my question above - how much testing have you done with SSO?

**Comment by matmair** [comment]
Ok now everything should be good to go

**Comment by SchrodingersGat** [comment]
@matmair OK, here we go! Let's be prepared for some error reports ;)

**Comment by matmair** [comment]
I already have a few PRs teed up to add some small stuff but I think it should be pretty robust from the error side

**Comment by matmair** [comment]
Thank you for the feeback
