### PR TITLE
fix(contrib): Invoke Path Issues

### LINKED ISSUE #8827: Invoke Path Issues
### Overview

A "bug" has been introduced since the merging of https://github.com/inventree/InvenTree/pull/8747 - the `invoke` commands no longer work as expected.

### Description

When calling `invoke` (used for most system commands), the loaded virtual environment is not used as expected.

This occurs when `invoke` is installed as a system-level package which is available on `PATH` with higher priority than the version installed in the python virtual environment.

The outcome is that calling `invoke <command>` *does not use* the packages installed in the InvenTree virtual environment.

### Example - System Invoke

`invoke version` - invoke installed at `/usr/bin/invoke`

```
Warning: Dulwich module not found, git information will not be available.

InvenTree - inventree.org
The Open-Source Inventory Management System


Python paths:
Executable  /usr/bin/python3
Environment /usr

Installation paths:
Base        /home/inventree
Config      /home/inventree/dev/config.yaml
Media       /home/inventree/dev/media
Static      /home/inventree/dev/static

Versions:
Python      3.11.8
Django      4.2.16
InvenTree   0.18.0 dev
API         297
Node        v18.20.1
Yarn        1.22.19

Commit hash: None
Commit date: None
```

### Example - venv invoke

`python -m invoke version` - called from InvenTree venv

```
InvenTree - inventree.org
The Open-Source Inventory Management System


Python paths:
Executable  /home/inventree/dev/venv/bin/python
Environment /home/inventree/dev/venv

Installation paths:
Base        /home/inventree
Config      /home/inventree/dev/config.yaml
Media       /home/inventree/dev/media
Static      /home/inventree/dev/static

Versions:
Python      3.11.8
Django      4.2.17
InvenTree   0.18.0 dev
API         297
Node        v18.20.1
Yarn        1.22.19

Commit hash: ea9e3fb
Commit date: 2025-01-05
```

_Originally posted by @SchrodingersGat in https://github.com/inventree/InvenTree/issues/8747#issuecomment-2571472624_

### PR DESCRIPTION
**Pull request by matmair**
Fixes #8827

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
This is a clever approach! Unfortunately it immediately fails on our devcontainer (which is running off the docker image).

This is because our docker image installs invoke as part of the base image, rather than into the venv.

image

**Comment by SchrodingersGat** [comment]
We could adjust our devcontainer post-install step to manually run `pip install -U invoke --ignore-installed` - and do similar things in our CI

**Comment by matmair** [comment]
@SchrodingersGat this check checks an environment variable that is set at the beginning of the base image - I think it is save to assume this should be available in any image build around our Dockerfile

**Comment by matmair** [comment]
If I understand our images correctly it is normal that the invoke path is not correct in them

**Comment by SchrodingersGat** [comment]
>  think it is save to assume this should be available in any image build around our Dockerfile

The exception here is that in the devcontainer setup, we install the python packages into a virtual environment (because we may need to change them during development). As such, the `invoke` version check then fails.

So I think a good addition here is that we specifically install another copy of invoke into this venv as part of the devcontainer post-install step.

Also, any devs who are using the devcontainer setup will need to run this command too. So we should add "breaking" tag to this PR

**Comment by matmair** [comment]
@SchrodingersGat implemented

File: .devcontainer/postCreateCommand.sh [hunk 1]
```diff
@@ -7,6 +7,9 @@ git config --global --add safe.directory /home/inventree
 python3 -m venv /home/inventree/dev/venv --system-site-packages --upgrade-deps
 . /home/inventree/dev/venv/bin/activate
 
+# Ensure the correct invoke is available
+pip3 install invoke
```
Comment (SchrodingersGat) [inline .devcontainer/postCreateCommand.sh:11]: You will need to add `--ignore-installed` to force it to install into the venv

Comment (matmair) [reply .devcontainer/postCreateCommand.sh]: Thank you, added

**Review by SchrodingersGat — APPROVED** [review]

**Comment by SchrodingersGat** [comment]
Thanks, hopefully this puts this issue to bed :)
